INSERT INTO person(full_name, birthday_year) VALUES('Александр Петров', 1940);
INSERT INTO person(full_name, birthday_year) VALUES('Анастасия Иванова', 1941);
INSERT INTO person(full_name, birthday_year) VALUES('Антон Сергеев', 1942);
INSERT INTO person(full_name, birthday_year) VALUES('Борис Зайцев', 1943);
INSERT INTO person(full_name, birthday_year) VALUES('Вадим Соколов', 1944);
INSERT INTO person(full_name, birthday_year) VALUES('Галина Романова', 1945);
INSERT INTO person(full_name, birthday_year) VALUES('Даниил Смирнов', 1946);
INSERT INTO person(full_name, birthday_year) VALUES('Екатерина Андреева', 1947);
INSERT INTO person(full_name, birthday_year) VALUES('Иван Сидоров', 1948);
INSERT INTO person(full_name, birthday_year) VALUES('Кирилл Козлов', 1949);
INSERT INTO person(full_name, birthday_year) VALUES('Лариса Орлова', 1950);
INSERT INTO person(full_name, birthday_year) VALUES('Максим Андреев', 1951);
INSERT INTO person(full_name, birthday_year) VALUES('Николай Романов', 1952);
INSERT INTO person(full_name, birthday_year) VALUES('Ольга Смирнова', 1953);
INSERT INTO person(full_name, birthday_year) VALUES('Павел Андреев', 1954);
INSERT INTO person(full_name, birthday_year) VALUES('Роман Сидоров', 1955);
INSERT INTO person(full_name, birthday_year) VALUES('Сергей Козлов', 1956);
INSERT INTO person(full_name, birthday_year) VALUES('Татьяна Орлова', 1957);
INSERT INTO person(full_name, birthday_year) VALUES('Ульяна Смирнова', 1958);
INSERT INTO person(full_name, birthday_year) VALUES('Федор Андреев', 1959);

INSERT INTO book(name,author,publish_year,owner_id) VALUES ('1984','Джордж Оруэлл', 1984, 17);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('О дивный новый мир','Олдос Хаксли', 1932, 1);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Великий Гэтсби','Ф. Скотт Фицджеральд', 1925, 4);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Тотошка','Агния Барто', 1969, 17);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Война и Мир','Лев Толстой', 1867, 8);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Превращение','Франц Кафка', 1915, 5);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Мастер и Маргарита','Михаил Булгаков', 1927, 16);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Убить пересмешника','Харпер Ли', 1935, 8);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Над пропастью во ржи','Дж. Д. Сэлинджер', 1951, 11);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Сто лет одиночества','Габриэль Гарсия Маркес', 1967, 15);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Лолита','Владимир Набоков', 1959, 9);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Прощай, оружие','Эрнест Хемингуэй', 1929, 18);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('451 градус по Фаренгейту','Рэй Брэдбери', 1953, 19);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Алхимик','Пауло Коэльо', 1988, 12);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Франкенштейн','Мэри Шелли', 1818, 3);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Автостопом по галактике','Дуглас Адамс', 1979, 14);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Мартин Иден','Джек Лондон', 1909, 15);
INSERT INTO book(name,author,publish_year,owner_id) VALUES ('Собака Баскервилей','Артур Конан Дойл', 1902, 16);